In [1]:
import numpy as np

List vs Numpy array time check


In [2]:
from time import process_time

Time taken by Lists


In [5]:
python_list = [i for i in range(100000000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

7.595652766000001


Time taken by Numpy array

In [6]:
numpy_array = np.array([i for i in range(100000000)])

start_time = process_time()

numpy_array += 5

end_time = process_time()

print(end_time - start_time)

0.0964563190000014


Numpy Arrays

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
np_array.shape

(5,)

In [9]:
b = np.array([[1,2,3,4,5],[6,7,8,9,19]])
b.shape

(2, 5)

In [10]:
x = np.zeros((4,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
y = np.ones((4,4,3))
y

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
np.full((4,3,5,4),4)

array([[[[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]]],


       [[[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]]],


       [[[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.random((5,6))

array([[0.38478557, 0.76777046, 0.56456204, 0.68480378, 0.83533416,
        0.4378305 ],
       [0.16600302, 0.58701664, 0.63590294, 0.07782029, 0.41651461,
        0.49512985],
       [0.04659998, 0.73747199, 0.01575945, 0.89011566, 0.16983951,
        0.23880634],
       [0.7323785 , 0.94936471, 0.41636154, 0.91575524, 0.35898187,
        0.63224092],
       [0.4068853 , 0.24363979, 0.59000744, 0.98935275, 0.40310297,
        0.31383495]])

In [15]:
np.random.randint(10,100,(3,5))

array([[69, 15, 57, 20, 61],
       [61, 32, 35, 29, 48],
       [59, 18, 81, 94, 69]])

In [16]:
np.linspace(4,20,6)

array([ 4. ,  7.2, 10.4, 13.6, 16.8, 20. ])

In [17]:
np.arange(4,30,5)

array([ 4,  9, 14, 19, 24, 29])

In [18]:
c = np.random.randint(2,40,(4,6))
c

array([[18, 28, 17, 18, 39, 20],
       [30, 29, 37, 35, 22,  3],
       [22, 29, 35, 17, 27,  8],
       [28, 11, 23, 17, 36, 34]])

In [19]:
c.shape

(4, 6)

In [20]:
c.ndim

2

In [21]:
c.size

24

In [22]:
c.dtype

dtype('int64')

In [23]:
a = np.random.randint(4,100,(4,3))
b = np.random.randint(4,100,(4,3))
print(a)
print(b)

[[27  8 71]
 [56 58 98]
 [95 62  9]
 [58  6 76]]
[[71 91 61]
 [21 49 55]
 [68 57 52]
 [36 86 57]]


In [24]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 98  99 132]
 [ 77 107 153]
 [163 119  61]
 [ 94  92 133]]
[[-44 -83  10]
 [ 35   9  43]
 [ 27   5 -43]
 [ 22 -80  19]]
[[1917  728 4331]
 [1176 2842 5390]
 [6460 3534  468]
 [2088  516 4332]]
[[0.38028169 0.08791209 1.16393443]
 [2.66666667 1.18367347 1.78181818]
 [1.39705882 1.0877193  0.17307692]
 [1.61111111 0.06976744 1.33333333]]


In [25]:
a.transpose()

array([[27, 56, 95, 58],
       [ 8, 58, 62,  6],
       [71, 98,  9, 76]])

In [26]:
a.T

array([[27, 56, 95, 58],
       [ 8, 58, 62,  6],
       [71, 98,  9, 76]])

In [28]:
b = a.reshape(2,6)
b

array([[27,  8, 71, 56, 58, 98],
       [95, 62,  9, 58,  6, 76]])